// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pmjnlbwchhphzcgwftlx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtam5sYndjaGhwaHpjZ3dmdGx4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyODk3NjMsImV4cCI6MjA1Nzg2NTc2M30.YCNVTbv65ATjLXFSKf_7jbLI_xKw9NIlrPzSf-sQsss";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);